### ISSUE TITLE
release编译出错

### ISSUE THREAD

**Issue by xocoder** [wtdcode/tun2socks#2]
debug编译正常，release编译dll出错。
具体错误如下：
`1>vj.c
1>slipif.c
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xtr1common(15): error C2061: 语法错误: 标识符“std”
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xtr1common(15): error C2059: 语法错误:“;”
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xtr1common(15): error C2449: 在文件范围内找到“{”(是否缺少函数头?)
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\xtr1common(337): error C2059: 语法错误:“}”
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(571): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_union”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(576): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_union”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(581): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_class”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(586): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_class”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(616): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_convertible_to”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(622): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_convertible_to”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(627): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_enum”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(632): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_enum”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(704): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_pod”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(709): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_pod”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(714): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_empty”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(719): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_empty”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(724): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_polymorphic”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(729): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_polymorphic”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(734): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_abstract”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(739): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_abstract”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(744): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_final”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(749): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_final”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(754): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_standard_layout”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(759): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_standard_layout”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(764): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_literal_type”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(771): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_literal_type”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(777): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivial”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(782): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivial”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(787): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_copyable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(792): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_copyable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(797): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__has_virtual_destructor”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(802): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__has_virtual_destructor”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(831): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(837): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(842): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(847): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(852): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(857): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(879): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(884): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(890): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(896): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(901): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(907): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(912): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(917): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(922): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_destructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(927): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_destructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(934): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(940): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(945): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(951): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(956): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(961): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(966): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(971): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(977): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(983): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(988): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(994): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(999): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1005): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1010): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_destructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1015): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_trivially_destructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1022): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1028): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1033): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1039): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1044): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1049): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1054): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1059): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_constructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1065): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1071): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1076): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1082): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1087): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1092): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_assignable”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1097): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_destructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1102): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_nothrow_destructible”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1363): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__underlying_type”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1430): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_base_of”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1436): error C4233: 使用了非标准扩展: 仅在 C++ 中支持“__is_base_of”关键字，C 中不支持
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\iosfwd(562): warning C4157: C 编译器忽略了杂注
1>d:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\iosfwd(569): warning C4157: C 编译器忽略了杂注
1>f:\pro\opensource\tun2socks-master\tun2socks-core\lwip\src\netif\slipif.c(559): fatal error C1004: 发现意外的文件尾
1>zepif.c
1>sys_arch.c
1>已完成生成项目“tun2socks-core.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========
`

**Comment by wtdcode** [comment]
可以试试全新版本 ：）
